#!/usr/bin/python3
"""Эмулятор запросов TMSERVER"""
from tornado.httpclient import HTTPRequest


order_denied_driver
order_crew_at_place
order_accepted
order_accepted
order_completed
order_offerred_driver
order_client_in_car
order_client_gone
order_client_fuck
order_client_fuck
order_no_cars
order_no_cars_aborted
order_client_fuck
order_aborted
order_created
order_crew_at_place
